language: node_js
node_js:
  - "iojs"

before_script:
  - chmod 755 ./.bin/*.sh
  - echo $TRAVIS_BRANCH
  - echo $DB_URL
  - echo $DB_URL$TRAVIS_BRANCH/plocal/graph
  - echo $DB_USER
  - sh -c ./.bin/create-travis-db.sh

after_script:
  - sh -c ./.bin/delete-travis-db.sh
